name: Update site with latest commit

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger subtree update in site repo
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.SITE_REPO_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/virain/virain.github.io/actions/workflows/update-content.yml/dispatches
