name: Update site with latest commit

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
     - name: Dispatch Event
       run: echo $TOKEN
