name: Update site with latest commit

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
     - name: Dispatch Event
       env:
        GITHUB_TOKEN: ${{ secrets.SITE_REPO_PAT }}
       run: |
         curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/virain/virain.github.io/actions/workflows/update-content.yml/dispatches \
          -d '{"ref":"v4"}'
