name: Update site with latest commit

on:
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  update-site:
    runs-on: ubuntu-latest
    steps:
     - name: Dispatch Event
       uses: flamestro/repository-event-dispatch-action@v1.1.0
       with:
        token: ${{ secrets.SITE_REPO_PAT }}
        event: update-content.yml
        repository: virain.github.io
        owner: virain
